#
# Kalisto
#
# Copyright (c) 2001-2010
#   Department of Distributed and Dependable Systems
#   Faculty of Mathematics and Physics
#   Charles University, Czech Republic
#
# Makefile for generating documentation using Doxygen
#

### Phony targets

.PHONY: all doc clean distclean

### Default target

all: doc

doc:
	doxygen

distclean: clean

clean:
	rm -rf html
